* Website
This repo contains the source files for my personal website, at [[nights.rest]]. It's inspired by console user interfaces and floating window managers, and uses some fun +hacks+ quirks to achieve it. The main website contains zero external libraries and is made entirely with vanilla HTML/CSS/JS, the only libraries are included in the different windows you can open, and are   limited to what I absolutely can't be bothered coding myself.
* How
The windows are simple HTML files with embedded JavaScript and CSS that get fetched and injected to the document using JavaScript.
Almost everything is based on the character width and height of a monospace font, which gets grabbed through reading the pixel height and pixel length of a div and dividing the length by the number of characters. 
It's fully static with no backend code and none of the code is bundled or minified (for now) for simplicity's sake, so feel free to read through it with the browser console.
* Compile
=build.sh= will bundle and minify JS and CSS files - and symlink others - into =dist/=
#+begin_src shell
  sh build.sh
#+end_src
* Things left to do
- [ ] Desktop icons for the windows
- [ ] A blog system
- [ ] Various bugfixes regarding window management

